[pytest]
filterwarnings =
    ignore:.*oneOf.*deprecated:UserWarning
    ignore:.*parseString.*deprecated:UserWarning
    ignore:.*resetCache.*deprecated:UserWarning
    ignore:.*deprecated.*use.*one_of:UserWarning
    ignore:.*deprecated.*use.*parse_string:UserWarning
    ignore:.*deprecated.*use.*reset_cache:UserWarning
    ignore:Conversion of an array with ndim > 0:DeprecationWarning
    ignore::pyparsing.core.PyparsingDeprecationWarning
